################################################################################
# Server Configuration
################################################################################

# System log (Morgan) prod or dev
LOG: prod

# Enable cors (cross-origin resource sharing)
CORS: true

# Webpack mode:
#   - development
#   - production 
MODE: production

# JWT user password encryption key (AUTH)
TOKEN_SECRET: token_secreto

# JWT life time
LIMIT_TOKEN:
  MIN: 14
  MAX: 30