---

- hosts: all
  gather_facts: false
  roles:
    - python

- hosts: nodes
  roles:
    - ddc
    - opennebula-repository
    - opennebula-node-kvm
    - opennebula-ssh
    - role: iptables
      iptables_base_rules_services:
        - { protocol: 'tcp', port: 22 }
        # TCP/179 bgpd (TODO: only needed on Route Refector(s))
        - { protocol: 'tcp', port: 179 }
        # TCP/8742 default VXLAN port on Linux (UDP/4789 default IANA)
        - { protocol: 'udp', port: 8472 }
    - update-replica
    - role: frr
      #bond0_0 is attached to the project private network
      frr_iface: 'bond0_0'
